'use client';

import { useMemo, useEffect, useRef, useState } from 'react';
import { useSessionStore } from '@/lib/store';
import { getSessionCalculations, getSessionAssignments } from '@/lib/firestore';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement } from 'chart.js';
import { Pie, Bar } from 'react-chartjs-2';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement);

const CHART_COLORS = [
    '#f59e42', '#3b82f6', '#10b981', '#8b5cf6', '#ef4444', '#eab308',
];

export default function CompletedMode() {
    const {
        session, participants, responsibilities, assignments, setAssignments,
        calculations, setCalculations,
    } = useSessionStore();

    const [loading, setLoading] = useState(true);
    const [showExport, setShowExport] = useState(false);
    const exportRef = useRef<HTMLTextAreaElement>(null);

    const activeResps = responsibilities.filter(r => r.status !== 'archived');
    const activeParticipants = participants.filter(p => p.status !== 'removed');

    useEffect(() => {
        async function loadResults() {
            if (!session) return;
            try {
                const [calcs, assigns] = await Promise.all([
                    getSessionCalculations(session.id),
                    getSessionAssignments(session.id),
                ]);
                setCalculations(calcs);
                setAssignments(assigns);
            } catch (err) {
                console.error(err);
            } finally {
                setLoading(false);
            }
        }
        loadResults();
    }, [session, setCalculations, setAssignments]);

    const sortedCalcs = useMemo(() =>
        [...calculations].sort((a, b) => b.final_equity - a.final_equity)
        , [calculations]);

    const pieData = {
        labels: sortedCalcs.map(c => c.participant_name),
        datasets: [{
            data: sortedCalcs.map(c => parseFloat(c.final_equity.toFixed(1))),
            backgroundColor: sortedCalcs.map((_, i) => CHART_COLORS[i % CHART_COLORS.length]),
            borderWidth: 0,
        }],
    };

    const barData = {
        labels: sortedCalcs.map(c => c.participant_name),
        datasets: [
            {
                label: 'Base Equity',
                data: sortedCalcs.map(c => parseFloat(c.base_equity.toFixed(1))),
                backgroundColor: '#3b82f6',
                borderRadius: 4,
            },
            {
                label: 'Final Equity',
                data: sortedCalcs.map(c => parseFloat(c.final_equity.toFixed(1))),
                backgroundColor: '#f59e42',
                borderRadius: 4,
            },
        ],
    };

    const chartOptions = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                labels: { color: '#94a3b8', font: { family: 'Inter' } },
            },
        },
        scales: {
            x: { ticks: { color: '#94a3b8' }, grid: { color: 'rgba(255,255,255,0.05)' } },
            y: { ticks: { color: '#94a3b8' }, grid: { color: 'rgba(255,255,255,0.05)' } },
        },
    };

    const generateMarkdown = (): string => {
        if (!session) return '';
        const lines: string[] = [];
        lines.push(`# Equity Distribution Report — ${session.business_name}`);
        lines.push(`Generated: ${new Date().toLocaleDateString()}`);
        lines.push('');
        lines.push('## Summary');
        lines.push('| Participant | Final Equity | Base Equity | Experience | Time | Investment |');
        lines.push('|---|---|---|---|---|---|');

        for (const c of sortedCalcs) {
            lines.push(`| ${c.participant_name} | **${c.final_equity.toFixed(1)}%** | ${c.base_equity.toFixed(1)}% | ×${c.experience_multiplier.toFixed(2)} | ×${c.time_multiplier.toFixed(2)} | ×${c.investment_multiplier.toFixed(2)} |`);
        }

        lines.push('');
        lines.push('## Responsibility Assignments');
        lines.push('| Responsibility | Assigned To | Weight | Shared |');
        lines.push('|---|---|---|---|');

        for (const resp of activeResps) {
            const assignedTo = assignments
                .filter(a => a.responsibility_id === resp.id)
                .map(a => activeParticipants.find(p => p.id === a.participant_id)?.name || 'Unknown');

            lines.push(`| ${resp.title} | ${assignedTo.join(', ') || '—'} | ${(resp.weight * 100).toFixed(1)}% | ${assignedTo.length > 1 ? 'Yes' : 'No'} |`);
        }

        lines.push('');
        lines.push('---');
        lines.push('*This report was generated by EquiSplit and is for informational purposes only. It does not constitute legal advice.*');

        return lines.join('\n');
    };

    const handleExport = () => {
        const md = generateMarkdown();
        setShowExport(true);
        setTimeout(() => {
            if (exportRef.current) {
                exportRef.current.value = md;
                exportRef.current.select();
            }
        }, 100);
    };

    const handleDownload = async () => {
        if (!session || !exportRef.current) return;
        setLoading(true);

        const content = document.getElementById('report-content');
        if (!content) return;

        try {
            const canvas = await html2canvas(content, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: '#F8F7FC', // match bg-primary
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'p',
                unit: 'mm',
                format: 'a4',
            });

            const imgWidth = 210; // A4 width in mm
            const pageHeight = 297; // A4 height in mm
            const imgHeight = (canvas.height * imgWidth) / canvas.width;
            let heightLeft = imgHeight;
            let position = 0;

            pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
            heightLeft -= pageHeight;

            while (heightLeft >= 0) {
                position = heightLeft - imgHeight;
                pdf.addPage();
                pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                heightLeft -= pageHeight;
            }

            pdf.save(`equity-report-${session.business_name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
        } catch (err) {
            console.error('PDF generation failed', err);
            alert('Failed to generate PDF. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <div className="loading-overlay">
                <div className="spinner spinner-lg" />
                <p>Loading results...</p>
            </div>
        );
    }

    if (sortedCalcs.length === 0) {
        return (
            <div className="empty-state">
                <div className="empty-state-icon">📊</div>
                <h2 className="empty-state-title">No Results Yet</h2>
                <p className="empty-state-text">The equity calculation hasn&apos;t been run yet.</p>
            </div>
        );
    }

    return (
        <div>
            <div className="flex justify-between items-center mb-xl">
                <div>
                    <h2 className="section-title">Equity Distribution Results</h2>
                    <p className="section-subtitle">Final equity split based on responsibilities, experience, time, and investment.</p>
                </div>
                <div className="flex gap-sm" data-html2canvas-ignore>
                    <button className="btn btn-secondary" onClick={handleExport}>📋 View Markdown</button>
                    <button className="btn btn-primary" onClick={handleDownload}>
                        {loading ? 'Generating PDF...' : '📥 Download Report (PDF)'}
                    </button>
                </div>
            </div>

            <div id="report-content" style={{ padding: '20px', background: '#F8F7FC' }}>

                {/* Equity Cards */}
                <div className="stat-grid" style={{ gridTemplateColumns: `repeat(${Math.min(sortedCalcs.length, 4)}, 1fr)` }}>
                    {sortedCalcs.map((calc, i) => (
                        <div key={calc.participant_id} className="card" style={{ textAlign: 'center', borderTop: `3px solid ${CHART_COLORS[i % CHART_COLORS.length]}` }}>
                            <div style={{ fontSize: 'var(--font-3xl)', fontWeight: 800, color: CHART_COLORS[i % CHART_COLORS.length] }}>
                                {calc.final_equity.toFixed(1)}%
                            </div>
                            <div className="font-semibold mb-sm">{calc.participant_name}</div>
                            <div className="text-xs text-muted">
                                Base: {calc.base_equity.toFixed(1)}% · Multiplier: ×{calc.combined_multiplier.toFixed(2)}
                            </div>
                            <div className="flex gap-xs justify-center mt-md flex-wrap">
                                <span className="badge badge-blue">Exp ×{calc.experience_multiplier.toFixed(2)}</span>
                                <span className="badge badge-green">Time ×{calc.time_multiplier.toFixed(2)}</span>
                                <span className="badge badge-yellow">Inv ×{calc.investment_multiplier.toFixed(2)}</span>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Charts */}
                <div className="grid-2 mb-xl" style={{ marginTop: 'var(--space-xl)' }}>
                    <div className="card" style={{ height: 350 }}>
                        <h3 className="card-title mb-md">Equity Distribution</h3>
                        <div style={{ height: 280 }}>
                            <Pie data={pieData} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { labels: { color: '#94a3b8', font: { family: 'Inter' } } } } }} />
                        </div>
                    </div>
                    <div className="card" style={{ height: 350 }}>
                        <h3 className="card-title mb-md">Base vs Final</h3>
                        <div style={{ height: 280 }}>
                            <Bar data={barData} options={chartOptions} />
                        </div>
                    </div>
                </div>

                {/* Detailed Breakdown */}
                <div className="card mb-xl">
                    <h3 className="card-title mb-md">📊 Detailed Breakdown</h3>
                    <div className="table-container">
                        <table>
                            <thead>
                                <tr>
                                    <th>Participant</th>
                                    <th>Base Weight</th>
                                    <th>Base Equity</th>
                                    <th>Exp ×</th>
                                    <th>Time ×</th>
                                    <th>Inv ×</th>
                                    <th>Combined ×</th>
                                    <th>Final Equity</th>
                                </tr>
                            </thead>
                            <tbody>
                                {sortedCalcs.map(c => (
                                    <tr key={c.participant_id}>
                                        <td className="font-semibold">{c.participant_name}</td>
                                        <td>{c.base_weight.toFixed(3)}</td>
                                        <td>{c.base_equity.toFixed(1)}%</td>
                                        <td>×{c.experience_multiplier.toFixed(2)}</td>
                                        <td>×{c.time_multiplier.toFixed(2)}</td>
                                        <td>×{c.investment_multiplier.toFixed(2)}</td>
                                        <td>×{c.combined_multiplier.toFixed(2)}</td>
                                        <td style={{ fontWeight: 700, color: 'var(--accent-solid)' }}>{c.final_equity.toFixed(1)}%</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* Assignment Matrix */}
                <div className="card mb-xl">
                    <h3 className="card-title mb-md">📋 Responsibility Assignment Matrix</h3>
                    <div className="table-container">
                        <table>
                            <thead>
                                <tr>
                                    <th>Responsibility</th>
                                    <th>Category</th>
                                    <th>Weight</th>
                                    {activeParticipants.map(p => <th key={p.id}>{p.name}</th>)}
                                </tr>
                            </thead>
                            <tbody>
                                {activeResps.sort((a, b) => a.category.localeCompare(b.category)).map(resp => (
                                    <tr key={resp.id}>
                                        <td className="font-semibold">{resp.title}</td>
                                        <td className="text-xs text-muted">{resp.category}</td>
                                        <td>{(resp.weight * 100).toFixed(1)}%</td>
                                        {activeParticipants.map(p => {
                                            const isAssigned = assignments.some(
                                                a => a.responsibility_id === resp.id && a.participant_id === p.id
                                            );
                                            return (
                                                <td key={p.id} style={{ textAlign: 'center' }}>
                                                    {isAssigned ? '✓' : '—'}
                                                </td>
                                            );
                                        })}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* Export Modal */}
                {showExport && (
                    <div className="modal-overlay" onClick={() => setShowExport(false)}>
                        <div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: 700 }}>
                            <div className="modal-header">
                                <h3 className="modal-title">Markdown Report</h3>
                                <button className="modal-close" onClick={() => setShowExport(false)}>✕</button>
                            </div>
                            <textarea
                                ref={exportRef}
                                className="form-textarea"
                                style={{ minHeight: 400, fontFamily: 'monospace', fontSize: '12px' }}
                                readOnly
                                defaultValue={generateMarkdown()}
                            />
                            <div className="modal-footer">
                                <button className="btn btn-secondary" onClick={() => {
                                    navigator.clipboard.writeText(generateMarkdown());
                                    alert('Copied to clipboard!');
                                }}>📋 Copy</button>
                                <button className="btn btn-primary" onClick={handleDownload}>📥 Download</button>
                            </div>
                        </div>
                    </div>
                )}

                <footer style={{ textAlign: 'center', padding: 'var(--space-xl) 0', color: 'var(--text-muted)', fontSize: 'var(--font-xs)' }}>
                    This report is for informational purposes only and does not constitute legal advice.
                    Consult a qualified attorney before finalizing any equity agreements.
                </footer>
            </div>
        </div>
    );
}
